=== asmexcaliburwoods/openwood/trunk/openmim-2.0/src/org/openmim/test/mns.dtd
<!-- <?xml encoding="UTF-8"?> -->

<!-- 

Script language is case-sensitive.


Possible numeric expressions:

- "Sany non-negative integer numberS",
- "SinfinityS",
- "SrandomS(SrangeStartS,SrangeEndS)S",

where S is optional whitespace, any non-negative integer number means any non-negative integer number, infinity [in a loop] means the eternal loop, rangeStart and rangeEnd are any integer numbers.

In places other than loop times the infinity value is not allowed.

<loop times="0"> means "do not execute the loop body."

Zero sleep time is allowed and means "skip the sleep."

-->

<!ELEMENT mns (define-user|behavior|launch-thread)+>

<!ELEMENT define-user EMPTY>
<!ATTLIST define-user nick      CDATA #REQUIRED>
<!ATTLIST define-user login-id  ID    #REQUIRED>
<!ATTLIST define-user password  CDATA #IMPLIED>

<!ELEMENT behavior (show-button|thread-meeting|log|loop|sleep|send-msg|add-contact-list-item|remove-contact-list-item|login|logout|set-status|on-msg)+>
<!ATTLIST behavior id       ID #REQUIRED>

<!ELEMENT launch-thread EMPTY>
<!ATTLIST launch-thread behavior-id   CDATA #REQUIRED>
<!ATTLIST launch-thread src-login-id  CDATA #REQUIRED>

<!ELEMENT loop (show-button|thread-meeting|log|loop|sleep|send-msg|add-contact-list-item|remove-contact-list-item|login|logout|set-status|on-msg)+>
<!ATTLIST loop times      CDATA 'infinity'>

<!ELEMENT sleep EMPTY>
<!ATTLIST sleep seconds     CDATA #IMPLIED>
<!ATTLIST sleep minutes     CDATA #IMPLIED>
<!-- either seconds or minutes is required -->

<!ELEMENT log EMPTY>
<!ATTLIST log msg CDATA #REQUIRED>

<!ELEMENT thread-meeting EMPTY>
<!ATTLIST thread-meeting barrier-participants-count   CDATA #REQUIRED>
<!ATTLIST thread-meeting meeting-id     ID    #REQUIRED>

<!ELEMENT show-button (#PCDATA)>  <!-- this PCdata is logged and also displayed as a label in a dialog -->
<!ATTLIST show-button button-text   CDATA 'Proceed'>
<!ATTLIST show-button skip-text   CDATA 'Skip all buttons'>

<!ELEMENT login (contact-list)>

<!ELEMENT contact-list (item)+>

<!ELEMENT item EMPTY>
<!ATTLIST item login-id     CDATA #REQUIRED>

<!ELEMENT logout EMPTY>

<!ELEMENT send-msg (#PCDATA)>
<!ATTLIST send-msg to     CDATA #REQUIRED>
<!ATTLIST send-msg type     CDATA #IMPLIED>  <!-- (null|'with-ascii-00-to-31-appended'|'with-readable-stuff-appended') -->
<!ATTLIST send-msg msg-size-chars CDATA #IMPLIED>

<!ELEMENT add-contact-list-item EMPTY>
<!ATTLIST add-contact-list-item dst-login-id CDATA #REQUIRED>

<!ELEMENT remove-contact-list-item EMPTY>
<!ATTLIST remove-contact-list-item dst-login-id CDATA #REQUIRED>

<!ELEMENT set-status EMPTY>
<!ATTLIST set-status status (online|offline|busy|random-online-busy) #REQUIRED>

<!ELEMENT on-msg (reply)+>

<!ELEMENT reply (#PCDATA)>

=== asmexcaliburwoods/openwood/openmim-2.0/src/org/openmim/test/functionality-test-script.mns.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mns SYSTEM "mns.dtd">
<mns>

  <!--
  nicks are for convinience.
  nicks can be used instead of login ids anywhere.

  examples:

  <define-user nick="jt12"  login-id="122500891" password="p"/>
  <define-user nick="jt14"  login-id="122994538" password="p"/>
  <define-user nick="jt15"  login-id="123014271" password="p"/>
  <define-user nick="devil" login-id="666"/>
  -->


  <!-- 
  launch as many java threads as needed. 

  behavior-ids and/or src-login-ids can be equal for 
  different threads.

  examples:

  <launch-thread behavior-id="be1" src-login-id="jt14"/>
  <launch-thread behavior-id="be1" src-login-id="jt15"/>
  <launch-thread behavior-id="be2" src-login-id="jt15"/>
  -->

  <!--
  behavior definitions.

  currently, on any operation exception,
  the corresponding interpreter thread
  simply finishes.
  
  example:

  <behavior id="be2">
    <sleep seconds="65"/>
    <logout/>
  </behavior>
  -->

<!--
Actors: 
Mobile applet user (associated with its messaging login id ‘mobile-applet-messaging-login-id’)
Native user (associated with its messaging login id ‘native-messaging-login-id’)
Test messaging plugin user ‘tmpc’ (associated with its messaging login id ‘tmpc-login-id’)
Test messaging plugin user 2 ‘tmpc2’ (associated with its messaging login id ‘tmpc2-login-id’)

  <define-user nick="jt12"  login-id="122500891" password="p"/>
  <define-user nick="jt14"  login-id="122994538" password="p"/>
  <define-user nick="jt15"  login-id="123014271" password="p"/>
-->

  <define-user nick="mobile-applet" login-id="123014271"/>
  <define-user nick="native" login-id="123014271"/>
  <define-user nick="tmpc" login-id="122994538" password="p"/>
  <define-user nick="tmpc2"  login-id="122500891" password="p"/>
  <define-user nick="invalid" login-id="1111111111" password="p"/>
  <define-user nick="random-contact1" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact2" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact3" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact4" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact5" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact6" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact7" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact8" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contact9" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contactA" login-id="random(100000, 100000000)"/>
  <define-user nick="random-contactB" login-id="random(100000, 100000000)"/>

<!--
3.2     Unit Test Cases for Messaging Network Plugin Unit
Scripts:
Script to test general functionality, contains definitions for both tmpc and tmpc2, implements test cases defined by 3.2.1.....3.2.7.

<launch-thread behavior-id="tmp" src-login-id="tmpc"/>
-->

  <launch-thread behavior-id="func-test-cases-3.2-inv" src-login-id="invalid"/>
  <launch-thread behavior-id="func-test-cases-3.2-tmpc" src-login-id="tmpc"/>
  <launch-thread behavior-id="func-test-cases-3.2-tmpc2" src-login-id="tmpc2"/>


  <behavior id="func-test-cases-3.2-inv">
        <thread-meeting barrier-participants-count="2" meeting-id="before-invalid"/>
        <log msg="### · Залогинить tmpc с невалидным login id, например “111111111111111111111” для icq network.  Плагин должен проигнорировать запрос и выдать ошибку."/>
        <try>
         <login>
          <contact-list>
            <item login-id="random-contact1"/>
            <item login-id="random-contact2"/>
            <item login-id="random-contact3"/>
            <item login-id="random-contact4"/>
            <item login-id="random-contact5"/>
            <item login-id="random-contact6"/>
            <item login-id="random-contact7"/>
            <item login-id="random-contact8"/>
            <item login-id="random-contact9"/>
            <item login-id="random-contactA"/>
            <item login-id="random-contactB"/>
          </contact-list>
         </login>
        <catch/>
        </try>
        <thread-meeting barrier-participants-count="2" meeting-id="after-invalid"/>
  </behavior>

  <behavior id="func-test-cases-3.2-tmpc">
        <log msg="### Functionality test cases."/>
        <log msg="### 3.2       Unit Test Cases for Messaging Network Plugin Unit"/>

        <thread-meeting barrier-participants-count="2" meeting-id="after-title"/>  

        <log msg="### 3.2.1     Управление клиентом"/>
        <log msg="### · Залогинить  tmpc"/>

        <login>
          <contact-list>
            <item login-id="random-contact1"/>
            <item login-id="random-contact2"/>
            <item login-id="random-contact3"/>
            <item login-id="random-contact4"/>
            <item login-id="random-contact5"/>
            <item login-id="random-contact6"/>
            <item login-id="random-contact7"/>
            <item login-id="random-contact8"/>
            <item login-id="random-contact9"/>
            <item login-id="random-contactA"/>
            <item login-id="random-contactB"/>
          </contact-list>
        </login>

        <log msg="### · Залогоффить tmpc"/>

        <logout/>

        <thread-meeting barrier-participants-count="2" meeting-id="before-invalid"/>

        <sleep seconds="20"/> <!-- this sleep is necessary to bypass relogin rate control exception  on the next login -->

        <thread-meeting barrier-participants-count="2" meeting-id="after-invalid"/>

        <log msg="### 3.2.1    Управление контакт листом"/>
        <log msg="### · Залогинить tmpc "/>

          <login>
            <contact-list>
              <item login-id="random-contact1"/>
              <item login-id="random-contact2"/>
              <item login-id="random-contact3"/>
              <item login-id="random-contact4"/>
              <item login-id="random-contact5"/>
              <item login-id="random-contact6"/>
              <item login-id="random-contact7"/>
              <item login-id="random-contact8"/>
              <item login-id="random-contact9"/>
              <item login-id="random-contactA"/>
            </contact-list>
          </login>

        <log msg="### · Добавить несколько (2-3) контактов в контакт лист of tmpc."/>

        <add-contact-list-item dst-login-id="random-contactB"/>
        <sleep seconds="1"/>  <!-- another rate control code needed! -->
        <loop times="random(1,2)">
          <add-contact-list-item dst-login-id="random(1000000, 10000000)"/>
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
        </loop>

        <log msg="### · Попробовать повторно добавить один из контактов, уже присутствующих в контакт листе of tmpc. Плагин должен молча проигнорировать данный запрос, контакт лист должен остаться неизменным."/>

        <add-contact-list-item dst-login-id="random-contactB"/>

        <log msg="### · Удалить несколько (5-10) контактов из контакт листа of tmpc."/>

        <remove-contact-list-item dst-login-id="random-contact1"/>
        <sleep seconds="1"/>  <!-- another rate control code needed! -->
        <remove-contact-list-item dst-login-id="random-contact2"/>
        <sleep seconds="1"/>  <!-- another rate control code needed! -->
        <remove-contact-list-item dst-login-id="random-contact3"/>
        <sleep seconds="1"/>  <!-- another rate control code needed! -->
        <remove-contact-list-item dst-login-id="random-contact4"/>
        <sleep seconds="1"/>  <!-- another rate control code needed! -->
        <remove-contact-list-item dst-login-id="random-contact5"/>
        
        <loop times="random(0,1)">
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
          <remove-contact-list-item dst-login-id="random-contact6"/>
        </loop>
        <loop times="random(0,1)">
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
          <remove-contact-list-item dst-login-id="random-contact7"/>
        </loop>
        <loop times="random(0,1)">
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
          <remove-contact-list-item dst-login-id="random-contact8"/>
        </loop>
        <loop times="random(0,1)">
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
          <remove-contact-list-item dst-login-id="random-contact9"/>
        </loop>
        <loop times="random(0,1)">
          <sleep seconds="1"/>  <!-- another rate control code needed! -->
          <remove-contact-list-item dst-login-id="random-contactA"/>
        </loop>

        <log msg="### 3.2.2     Управление состоянием"/>
        <log msg="### · Сменить статус of tmpc на Offline. В контакт листах нативного  клиента и mobile апплет клиента, в которых login id of tmpc содержится как контакт, должно произойти изменение его состояния на Offline."/>

        <set-status status="offline"/>
        <sleep seconds="20"/>
        
        <log msg="### · Залогинить tmpc с начальным статусом Online. В контакт листах нативного  клиента и mobile апплет клиента, в которых login id of tmpc содержится как контакт, должно произойти изменение его состояния на Online."/>

        <login>
          <contact-list>
            <item login-id="random-contact1"/>
            <item login-id="random-contact2"/>
            <item login-id="random-contact3"/>
            <item login-id="random-contact4"/>
            <item login-id="random-contact5"/>
            <item login-id="random-contact6"/>
            <item login-id="random-contact7"/>
            <item login-id="random-contact8"/>
            <item login-id="random-contact9"/>
